# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragruntbucket-ieu72"
    dynamodb_table = "courses-lock-table"
    encrypt        = true
    key            = "us-east-1/./terraform.tfvars"
    profile        = "default"
    region         = "us-east-1"
  }
}
